# Generated by Django 3.1.7 on 2021-03-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('competen', models.IntegerField(default=1)),
                ('teach', models.IntegerField(default=1)),
                ('punc', models.IntegerField(default=1)),
                ('prac', models.IntegerField(default=1)),
                ('approach', models.IntegerField(default=1)),
                ('classcontrol', models.IntegerField(default=1)),
            ],
        ),
    ]
